@ECHO OFF

@REM SET WORKSTATION SPECIFIC ENVIRONMENT VARIABLES
SET "PEGASUS_LOCATION="
SET "PEGASUS_LOCATION_PYTHON="
SET "PEGASUS_LOG_DIRECTORY="

@REM SET GITHUB ENVIRONMENT VARIABLES
SET "PEGASUS_GITHUB_PAT="

@REM SET PEGASUS DATABASE ENVIRONMENT VARIABLES
SET "PEGASUS_DB_NAME=pegasus.sqlite"
SET "PEGASUS_DB_TABLE_PREFIX=peg_"

@REM SET PEGASUS CALL WATCHER ENVIRONMENT VARIABLES
SET "PEGASUS_LOG_FILE_PREFIX=log"
SET "PEGASUS_LOG_FILE_SUFFIX=.txt"
SET "PEGASUS_CALL_STRING_PREFIX=Call Placed"
SET "PEGASUS_CALL_LOG_COLUMNS=7"
