@ECHO OFF

@REM SET WORKSTATION SPECIFIC ENVIRONMENT VARIABLES
SET "PEGASUS_LOCATION=D:\Default\Documents\Business\projects\_AAA_pegasus"
SET "PEGASUS_LOCATION_PYTHON=D:\Python\Python38"
SET "PEGASUS_LOG_DIRECTORY=D:\temp"

@REM SET GITHUB ENVIRONMENT VARIABLES
SET "PEGASUS_GITHUB_PAT="
